/**
 * Realistic Mock Data Seed for Smart India Hackathon GeM Evaluation Engine
 * Includes Government RFP Tenders, Strict RFP Requirement Clauses,
 * Bidder Document Packets with OCR bounding boxes, and initial Audit Logs.
 */

import { Tender, Requirement, Bidder, AuditLog } from '../types';

export const MOCK_REQUIREMENTS: Requirement[] = [
  {
    id: 'req-r001',
    tender_id: 'tender-gem-2026-cloud',
    clause_code: 'R001',
    clause_title: 'Minimum Average Annual Turnover',
    description: 'The minimum average annual turnover of the bidder during the last 3 financial years must be at least ₹3.00 Crores, certified by a Chartered Accountant with valid UDIN.',
    category: 'FINANCIAL',
    rule_type: 'NUMERIC_GTE',
    threshold_value: '30000000',
    threshold_display: '₹3.00 Crores (Avg last 3 FY)',
    is_mandatory: true,
    weight: 25,
  },
  {
    id: 'req-r002',
    tender_id: 'tender-gem-2026-cloud',
    clause_code: 'R002',
    clause_title: 'Past Operational Experience',
    description: 'Bidder must possess a minimum of 5 years continuous operational experience executing enterprise IT hardware / cloud infrastructure contracts for Govt/PSU/Scheduled Commercial entities.',
    category: 'EXPERIENCE',
    rule_type: 'NUMERIC_GTE',
    threshold_value: '5',
    threshold_display: 'Min 5 Years Active Experience',
    is_mandatory: true,
    weight: 20,
  },
  {
    id: 'req-r003',
    tender_id: 'tender-gem-2026-cloud',
    clause_code: 'R003',
    clause_title: 'Statutory GST Registration Validity',
    description: 'Bidder must hold an Active Form GST REG-06 registration certificate valid on the date of bid submission with no record of cancellation or non-filing suspension.',
    category: 'STATUTORY',
    rule_type: 'DATE_BEFORE',
    threshold_value: 'ACTIVE',
    threshold_display: 'Active GSTIN through Bid Closing',
    is_mandatory: true,
    weight: 20,
  },
  {
    id: 'req-r004',
    tender_id: 'tender-gem-2026-cloud',
    clause_code: 'R004',
    clause_title: 'Non-Debarment / Anti-Blacklisting Affidavit',
    description: 'Bidder must furnish a notarized affidavit affirming non-debarment and verify clean standing on the Central Public Procurement Portal (CPPP) National Debarment Database.',
    category: 'STATUTORY',
    rule_type: 'EXACT_MATCH',
    threshold_value: 'CLEAR',
    threshold_display: 'Zero Debarment / CPPP Clear',
    is_mandatory: true,
    weight: 15,
  },
  {
    id: 'req-r005',
    tender_id: 'tender-gem-2026-cloud',
    clause_code: 'R005',
    clause_title: 'OEM Authorization Form (MAF)',
    description: 'Bidder must submit a verifiable Manufacturer Authorization Form from OEM (Cisco/Dell/HPE) specifically tied to this GeM Tender. Legal entity name must match bidder documentation.',
    category: 'OEM',
    rule_type: 'EXISTS',
    threshold_value: 'VALID_OEM_MAF',
    threshold_display: 'OEM Authorized Partner Certification',
    is_mandatory: true,
    weight: 15,
  },
  {
    id: 'req-r006',
    tender_id: 'tender-gem-2026-cloud',
    clause_code: 'R006',
    clause_title: 'MSME / Udyam Make-in-India Preference',
    description: 'Valid Udyam Registration Certificate for MSE purchase preference and tender fee / EMD exemption under Public Procurement Policy (PPP-MSE).',
    category: 'TECHNICAL',
    rule_type: 'EXACT_MATCH',
    threshold_value: 'VERIFIED_MSME',
    threshold_display: 'Udyam MSE Validated',
    is_mandatory: false,
    weight: 5,
  },
];

export const MOCK_TENDER: Tender = {
  id: 'tender-gem-2026-cloud',
  tender_number: 'GEM/2026/B/892104',
  title: 'Procurement of High-End Enterprise Cloud Servers & Networking Hardware for National Data Centers',
  department: 'Ministry of Electronics and Information Technology (MeitY), National Informatics Centre (NIC)',
  estimated_budget: 45000000, // ₹4.50 Crores
  budget_formatted: '₹4.50 Crores',
  deadline: '2026-10-15T18:00:00Z',
  created_at: '2026-08-20T10:00:00Z',
  requirements: MOCK_REQUIREMENTS,
};

export const MOCK_TENDERS: Tender[] = [
  MOCK_TENDER,
  {
    id: 'tender-gem-2026-surveillance',
    tender_number: 'GEM/2026/B/774012',
    title: 'Deployment of AI-Powered Integrated Border Surveillance and Perimeter Security System',
    department: 'Ministry of Home Affairs (MHA), Border Security Force (BSF)',
    estimated_budget: 125000000,
    budget_formatted: '₹12.50 Crores',
    deadline: '2026-11-20T17:00:00Z',
    created_at: '2026-08-25T11:00:00Z',
    requirements: MOCK_REQUIREMENTS,
  },
  {
    id: 'tender-gem-2026-datacenter',
    tender_number: 'GEM/2026/B/651098',
    title: 'Procurement of High-Capacity Tier-IV Data Center SAN Storage and DR Replication Infrastructure',
    department: 'Ministry of Finance, Department of Revenue / Central Board of Direct Taxes (CBDT)',
    estimated_budget: 85000000,
    budget_formatted: '₹8.50 Crores',
    deadline: '2026-10-30T15:00:00Z',
    created_at: '2026-09-01T09:30:00Z',
    requirements: MOCK_REQUIREMENTS,
  },
];

export const MOCK_BIDDERS: Bidder[] = [
  {
    id: 'bidder-01',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'Bharat Datatech Solutions Private Limited',
    gst_number: '07AAACB1234F1Z8',
    pan_number: 'AAACB1234F',
    udyam_registration: 'UDYAM-DL-01-0089123',
    cin_number: 'U72200DL2017PTC321456',
    contact_person: 'Rajesh Sharma (Director)',
    contact_email: 'compliance@bharatdatatech.in',
    submission_date: '2026-09-02T14:30:00Z',
    overall_score: 96,
    risk_level: 'LOW',
    officer_decision: 'PENDING',
    decision_notes: 'Automated verification completed: 100% clause compliance and green external registries.',
    documents: [
      {
        id: 'doc-01-gst',
        bidder_id: 'bidder-01',
        file_name: 'GST_Registration_Certificate_REG06.pdf',
        doc_type: 'GST_CERT',
        file_url: '/docs/bidders/01/gst_cert.pdf',
        upload_date: '2026-09-02T14:15:00Z',
        page_count: 3,
        parsed_metadata: {
          extracted_entity_name: 'Bharat Datatech Solutions Private Limited',
          extracted_gstin: '07AAACB1234F1Z8',
          extracted_pan: 'AAACB1234F',
          valid_from: '2017-08-14',
          valid_until: '2030-12-31',
          issuing_authority: 'Central GST Delhi West Commissionerate',
          ocr_quality_score: 0.99,
        },
      },
      {
        id: 'doc-01-audit',
        bidder_id: 'bidder-01',
        file_name: 'CA_Audited_Financial_Statement_FY23_FY25.pdf',
        doc_type: 'FINANCIAL_AUDIT',
        file_url: '/docs/bidders/01/financial_audit.pdf',
        upload_date: '2026-09-02T14:20:00Z',
        page_count: 24,
        parsed_metadata: {
          extracted_entity_name: 'Bharat Datatech Solutions Private Limited',
          extracted_turnover: 52000000, // ₹5.20 Cr
          extracted_turnover_raw: '₹5,20,40,000 (Average for 3 FY)',
          issuing_authority: 'Gupta & Associates Chartered Accountants (FRN 014522N)',
          ocr_quality_score: 0.98,
        },
      },
      {
        id: 'doc-01-oem',
        bidder_id: 'bidder-01',
        file_name: 'Dell_Technologies_OEM_MAF_Authorization.pdf',
        doc_type: 'OEM_AUTH',
        file_url: '/docs/bidders/01/oem_maf.pdf',
        upload_date: '2026-09-02T14:22:00Z',
        page_count: 2,
        parsed_metadata: {
          extracted_entity_name: 'Bharat Datatech Solutions Private Limited',
          oem_authorized_brands: ['Dell PowerEdge R760', 'Dell PowerSwitch N3248'],
          issuing_authority: 'Dell Global B.V. (India Enterprise Division)',
          ocr_quality_score: 0.97,
        },
      },
      {
        id: 'doc-01-exp',
        bidder_id: 'bidder-01',
        file_name: 'NIC_Past_Experience_Completion_Cert.pdf',
        doc_type: 'WORK_ORDER_EXPERIENCE',
        file_url: '/docs/bidders/01/experience_cert.pdf',
        upload_date: '2026-09-02T14:25:00Z',
        page_count: 8,
        parsed_metadata: {
          extracted_years_experience: 7,
          extracted_entity_name: 'Bharat Datatech Solutions Private Limited',
          ocr_quality_score: 0.96,
        },
      },
      {
        id: 'doc-01-affidavit',
        bidder_id: 'bidder-01',
        file_name: 'Non_Debarment_Affidavit_Notarized.pdf',
        doc_type: 'AFFIDAVIT_BLACKLIST',
        file_url: '/docs/bidders/01/affidavit.pdf',
        upload_date: '2026-09-02T14:28:00Z',
        page_count: 2,
        parsed_metadata: {
          extracted_entity_name: 'Bharat Datatech Solutions Private Limited',
          ocr_quality_score: 0.98,
        },
      },
      {
        id: 'doc-01-udyam',
        bidder_id: 'bidder-01',
        file_name: 'Udyam_Registration_Certificate_MSME.pdf',
        doc_type: 'UDYAM',
        file_url: '/docs/bidders/01/udyam.pdf',
        upload_date: '2026-09-02T14:29:00Z',
        page_count: 2,
        parsed_metadata: {
          extracted_udyam_category: 'Medium',
          extracted_entity_name: 'Bharat Datatech Solutions Private Limited',
          ocr_quality_score: 0.99,
        },
      },
    ],
  },
  {
    id: 'bidder-02',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'Apex Infoways India Private Limited',
    gst_number: '27AABCA5678K1ZQ',
    pan_number: 'AABCA5678K',
    udyam_registration: 'UDYAM-MH-02-0045612',
    cin_number: 'U72900MH2019PTC298711',
    contact_person: 'Pooja Deshmukh (VP Bid Management)',
    contact_email: 'tenders@apexinfoways.co.in',
    submission_date: '2026-09-03T11:15:00Z',
    overall_score: 76,
    risk_level: 'MEDIUM',
    officer_decision: 'CLARIFICATION_REQUESTED',
    decision_notes: 'Entity name variation detected between GST and OEM authorization form. Officer clarification initiated.',
    documents: [
      {
        id: 'doc-02-gst',
        bidder_id: 'bidder-02',
        file_name: 'GST_Certificate_Apex_Infoways.pdf',
        doc_type: 'GST_CERT',
        file_url: '/docs/bidders/02/gst_cert.pdf',
        upload_date: '2026-09-03T10:45:00Z',
        page_count: 3,
        parsed_metadata: {
          extracted_entity_name: 'Apex Infoways India Private Limited',
          extracted_gstin: '27AABCA5678K1ZQ',
          extracted_pan: 'AABCA5678K',
          valid_from: '2019-02-10',
          valid_until: '2032-12-31',
          ocr_quality_score: 0.96,
        },
      },
      {
        id: 'doc-02-audit',
        bidder_id: 'bidder-02',
        file_name: 'Audited_Balance_Sheet_3Y_Turnover.pdf',
        doc_type: 'FINANCIAL_AUDIT',
        file_url: '/docs/bidders/02/audit.pdf',
        upload_date: '2026-09-03T10:50:00Z',
        page_count: 18,
        parsed_metadata: {
          extracted_entity_name: 'Apex Infoways India Private Limited',
          extracted_turnover: 31500000, // ₹3.15 Cr (just above 3.0 Cr)
          extracted_turnover_raw: '₹3,15,00,000 INR',
          ocr_quality_score: 0.94,
        },
      },
      {
        id: 'doc-02-oem',
        bidder_id: 'bidder-02',
        file_name: 'Cisco_OEM_Manufacturer_Auth.pdf',
        doc_type: 'OEM_AUTH',
        file_url: '/docs/bidders/02/cisco_maf.pdf',
        upload_date: '2026-09-03T10:55:00Z',
        page_count: 2,
        parsed_metadata: {
          // Notice: Name variance with GST! "Apex Infowayz Technologies Pvt Ltd" vs "Apex Infoways India Private Limited"
          extracted_entity_name: 'Apex Infowayz Technologies Pvt Ltd',
          oem_authorized_brands: ['Cisco Nexus 9000 Series', 'Cisco Catalyst 9300'],
          issuing_authority: 'Cisco Systems Capital (India) Pvt Ltd',
          ocr_quality_score: 0.95,
        },
      },
      {
        id: 'doc-02-exp',
        bidder_id: 'bidder-02',
        file_name: 'Work_Experience_Certificates.pdf',
        doc_type: 'WORK_ORDER_EXPERIENCE',
        file_url: '/docs/bidders/02/experience.pdf',
        upload_date: '2026-09-03T11:00:00Z',
        page_count: 6,
        parsed_metadata: {
          extracted_years_experience: 5,
          ocr_quality_score: 0.92,
        },
      },
      {
        id: 'doc-02-affidavit',
        bidder_id: 'bidder-02',
        file_name: 'Affidavit_Non_Blacklisting.pdf',
        doc_type: 'AFFIDAVIT_BLACKLIST',
        file_url: '/docs/bidders/02/affidavit.pdf',
        upload_date: '2026-09-03T11:05:00Z',
        page_count: 2,
        parsed_metadata: {
          extracted_entity_name: 'Apex Infoways India Private Limited',
          ocr_quality_score: 0.97,
        },
      },
      {
        id: 'doc-02-udyam',
        bidder_id: 'bidder-02',
        file_name: 'Udyam_MSME_Small_Enterprise.pdf',
        doc_type: 'UDYAM',
        file_url: '/docs/bidders/02/udyam.pdf',
        upload_date: '2026-09-03T11:10:00Z',
        page_count: 2,
        parsed_metadata: {
          extracted_udyam_category: 'Small',
          extracted_entity_name: 'Apex Infoways India Private Limited',
          ocr_quality_score: 0.98,
        },
      },
    ],
  },
  {
    id: 'bidder-03',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'Global Nexus Technologies Limited',
    gst_number: '33AAACD9999L1ZM',
    pan_number: 'AAACD9999L',
    udyam_registration: 'UDYAM-TN-03-0099881',
    cin_number: 'U72200TN2015PLC099999',
    contact_person: 'Karthik Venkataraman (Managing Director)',
    contact_email: 'karthik@nexusglobitech.org',
    submission_date: '2026-09-04T09:40:00Z',
    overall_score: 28,
    risk_level: 'HIGH',
    officer_decision: 'DISQUALIFIED',
    decision_notes: 'Mandatory statutory rejection: Vendor is listed in CPPP Debarment registry. GST registration is cancelled.',
    documents: [
      {
        id: 'doc-03-gst',
        bidder_id: 'bidder-03',
        file_name: 'Old_GST_Registration_Notice.pdf',
        doc_type: 'GST_CERT',
        file_url: '/docs/bidders/03/gst.pdf',
        upload_date: '2026-09-04T09:10:00Z',
        page_count: 2,
        parsed_metadata: {
          extracted_entity_name: 'Global Nexus Technologies Limited',
          extracted_gstin: '33AAACD9999L1ZM',
          extracted_pan: 'AAACD9999L',
          valid_until: '2023-01-01', // Expired
          ocr_quality_score: 0.88,
        },
      },
      {
        id: 'doc-03-audit',
        bidder_id: 'bidder-03',
        file_name: 'Unaudited_Balance_Sheet.pdf',
        doc_type: 'FINANCIAL_AUDIT',
        file_url: '/docs/bidders/03/audit.pdf',
        upload_date: '2026-09-04T09:15:00Z',
        page_count: 8,
        parsed_metadata: {
          extracted_entity_name: 'Global Nexus Technologies Limited',
          extracted_turnover: 18000000, // Only 1.8 Cr (required 3.0 Cr)
          extracted_turnover_raw: '1.80 Crores',
          ocr_quality_score: 0.89,
        },
      },
      // Note: OEM Authorization document is MISSING!
      {
        id: 'doc-03-exp',
        bidder_id: 'bidder-03',
        file_name: 'Client_List_Summary.pdf',
        doc_type: 'WORK_ORDER_EXPERIENCE',
        file_url: '/docs/bidders/03/exp.pdf',
        upload_date: '2026-09-04T09:20:00Z',
        page_count: 3,
        parsed_metadata: {
          extracted_years_experience: 3, // required 5
          ocr_quality_score: 0.87,
        },
      },
      {
        id: 'doc-03-affidavit',
        bidder_id: 'bidder-03',
        file_name: 'Self_Declaration_Affidavit.pdf',
        doc_type: 'AFFIDAVIT_BLACKLIST',
        file_url: '/docs/bidders/03/affidavit.pdf',
        upload_date: '2026-09-04T09:25:00Z',
        page_count: 1,
        parsed_metadata: {
          extracted_entity_name: 'Global Nexus Technologies Limited',
          ocr_quality_score: 0.91,
        },
      },
    ],
  },
];

export const MOCK_AUDIT_LOGS: Record<string, AuditLog[]> = {
  'bidder-01': [
    {
      id: 'log-01-1',
      tender_id: 'tender-gem-2026-cloud',
      bidder_id: 'bidder-01',
      actor: 'SYSTEM',
      action: 'DOCUMENT_PACKET_INGESTION_COMPLETED',
      timestamp: '2026-09-02T14:31:10Z',
      metadata: {
        documents_processed: 6,
        ocr_engine: 'Hybrid LayoutLMv3 + PyMuPDF FastExtractor',
        avg_confidence: 0.98,
      },
    },
    {
      id: 'log-01-2',
      tender_id: 'tender-gem-2026-cloud',
      bidder_id: 'bidder-01',
      actor: 'SYSTEM',
      action: 'EXTERNAL_REGISTRY_ADAPTERS_EVALUATED',
      timestamp: '2026-09-02T14:31:12Z',
      metadata: {
        gstn_status: 'ACTIVE',
        gstn_compliance_score: 98,
        udyam_category: 'Medium',
        debarment_status: 'CLEAR',
        execution_latency_ms: 312,
      },
    },
    {
      id: 'log-01-3',
      tender_id: 'tender-gem-2026-cloud',
      bidder_id: 'bidder-01',
      actor: 'SYSTEM',
      action: 'DETERMINISTIC_COMPLIANCE_RUN_COMPLETED',
      timestamp: '2026-09-02T14:31:14Z',
      metadata: {
        score: 96,
        risk_level: 'LOW',
        mandatory_failures_count: 0,
        recommendation: 'QUALIFIED',
      },
    },
  ],
  'bidder-02': [
    {
      id: 'log-02-1',
      tender_id: 'tender-gem-2026-cloud',
      bidder_id: 'bidder-02',
      actor: 'SYSTEM',
      action: 'DOCUMENT_PACKET_INGESTION_COMPLETED',
      timestamp: '2026-09-03T11:16:00Z',
      metadata: { documents_processed: 6 },
    },
    {
      id: 'log-02-2',
      tender_id: 'tender-gem-2026-cloud',
      bidder_id: 'bidder-02',
      actor: 'SYSTEM',
      action: 'CROSS_ENTITY_MISMATCH_DETECTED',
      timestamp: '2026-09-03T11:16:04Z',
      metadata: {
        clause: 'R005',
        doc1_entity: 'Apex Infoways India Private Limited',
        doc2_entity: 'Apex Infoways Technologies Pvt Ltd',
        normalized_levenshtein_distance: 0.14,
        similarity_percentage: 86,
        flag: '⚠️ ENTITY_NAME_MISMATCH',
      },
    },
    {
      id: 'log-02-3',
      tender_id: 'tender-gem-2026-cloud',
      bidder_id: 'bidder-02',
      actor: 'OFFICER',
      action: 'OFFICER_REQUESTED_CLARIFICATION',
      timestamp: '2026-09-04T10:15:30Z',
      metadata: {
        officer_name: 'Shri V. Ramaswamy (Joint Director, Procurement)',
        remarks: 'Issued formal GeM notice to Bidder requesting Board Resolution clarifying name difference between GST Certificate and Cisco MAF.',
      },
    },
  ],
  'bidder-03': [
    {
      id: 'log-03-1',
      tender_id: 'tender-gem-2026-cloud',
      bidder_id: 'bidder-03',
      actor: 'SYSTEM',
      action: 'CRITICAL_REGISTRY_BREACH_DETECTED',
      timestamp: '2026-09-04T09:41:20Z',
      metadata: {
        debarment_alert: true,
        order_number: 'MOD/PROC/DEBAR/2023/1892',
        debarring_agency: 'Ministry of Defence, DGOF Procurement Cell',
        gstn_status: 'CANCELLED',
      },
    },
    {
      id: 'log-03-2',
      tender_id: 'tender-gem-2026-cloud',
      bidder_id: 'bidder-03',
      actor: 'SYSTEM',
      action: 'AUTOMATIC_HIGH_RISK_OVERRIDE',
      timestamp: '2026-09-04T09:41:22Z',
      metadata: {
        risk_level: 'HIGH',
        score: 28,
        recommendation: 'DISQUALIFIED',
      },
    },
    {
      id: 'log-03-3',
      tender_id: 'tender-gem-2026-cloud',
      bidder_id: 'bidder-03',
      actor: 'OFFICER',
      action: 'OFFICER_DISQUALIFICATION_CONFIRMED',
      timestamp: '2026-09-04T16:00:00Z',
      metadata: {
        officer_name: 'Shri V. Ramaswamy (Joint Director, Procurement)',
        remarks: 'Disqualified under GFR Rule 151(iii) pursuant to active debarment order MOD/PROC/DEBAR/2023/1892. Retaining EMD under scrutiny.',
      },
    },
  ],
};
