/**
 * Realistic Mock Data Seed for Smart India Hackathon GeM Evaluation Engine
 * Includes Government RFP Tenders, Strict RFP Requirement Clauses,
 * Exactly 20 Bidder Document Packets with OCR metadata, and Cryptographic Audit Logs.
 * Strictly uses fictional alphabet-style company names (ABCD, BCDE, ... TUVW)
 * and zero real-world identity data.
 */

import { Tender, Requirement, Bidder, AuditLog } from '../types';

export const MOCK_REQUIREMENTS: Requirement[] = [
  {
    id: 'req-r001',
    tender_id: 'tender-gem-2026-cloud',
    clause_code: 'R001',
    clause_title: 'Minimum Average Annual Turnover',
    description: 'The minimum average annual turnover of the bidder during the last 3 financial years must be at least ₹3.00 Crores, certified by a Chartered Accountant with valid UDIN.',
    category: 'FINANCIAL',
    rule_type: 'NUMERIC_GTE',
    threshold_value: '30000000',
    threshold_display: '₹3.00 Crores (Avg last 3 FY)',
    is_mandatory: true,
    weight: 25,
  },
  {
    id: 'req-r002',
    tender_id: 'tender-gem-2026-cloud',
    clause_code: 'R002',
    clause_title: 'Past Operational Experience',
    description: 'Bidder must possess a minimum of 5 years continuous operational experience executing enterprise IT hardware / cloud infrastructure contracts for Govt/PSU/Scheduled Commercial entities.',
    category: 'EXPERIENCE',
    rule_type: 'NUMERIC_GTE',
    threshold_value: '5',
    threshold_display: 'Min 5 Years Active Experience',
    is_mandatory: true,
    weight: 20,
  },
  {
    id: 'req-r003',
    tender_id: 'tender-gem-2026-cloud',
    clause_code: 'R003',
    clause_title: 'Statutory GST Registration Validity',
    description: 'Bidder must hold an Active Form GST REG-06 registration certificate valid on the date of bid submission with no record of cancellation or non-filing suspension.',
    category: 'STATUTORY',
    rule_type: 'DATE_BEFORE',
    threshold_value: 'ACTIVE',
    threshold_display: 'Active GSTIN through Bid Closing',
    is_mandatory: true,
    weight: 20,
  },
  {
    id: 'req-r004',
    tender_id: 'tender-gem-2026-cloud',
    clause_code: 'R004',
    clause_title: 'Non-Debarment / Anti-Blacklisting Affidavit',
    description: 'Bidder must furnish a notarized affidavit affirming non-debarment and verify clean standing on the Central Public Procurement Portal (CPPP) National Debarment Database.',
    category: 'STATUTORY',
    rule_type: 'EXACT_MATCH',
    threshold_value: 'CLEAR',
    threshold_display: 'Zero Debarment / CPPP Clear',
    is_mandatory: true,
    weight: 15,
  },
  {
    id: 'req-r005',
    tender_id: 'tender-gem-2026-cloud',
    clause_code: 'R005',
    clause_title: 'OEM Authorization Form (MAF)',
    description: 'Bidder must submit a verifiable Manufacturer Authorization Form from authorized OEM specifically tied to this GeM Tender. Legal entity name must match bidder documentation.',
    category: 'OEM',
    rule_type: 'EXISTS',
    threshold_value: 'VALID_OEM_MAF',
    threshold_display: 'OEM Authorized Partner Certification',
    is_mandatory: true,
    weight: 15,
  },
  {
    id: 'req-r006',
    tender_id: 'tender-gem-2026-cloud',
    clause_code: 'R006',
    clause_title: 'MSME / Udyam Make-in-India Preference',
    description: 'Valid Udyam Registration Certificate for MSE purchase preference and tender fee / EMD exemption under Public Procurement Policy (PPP-MSE).',
    category: 'TECHNICAL',
    rule_type: 'EXACT_MATCH',
    threshold_value: 'VERIFIED_MSME',
    threshold_display: 'Udyam MSE Validated',
    is_mandatory: false,
    weight: 5,
  },
];

export const MOCK_TENDER: Tender = {
  id: 'tender-gem-2026-cloud',
  tender_number: 'GEM/2026/B/892104',
  title: 'Procurement of High-End Enterprise Cloud Servers & Networking Hardware for National Data Centers',
  department: 'Department of Public Procurement & IT Infrastructure',
  estimated_budget: 45000000, // ₹4.50 Crores
  budget_formatted: '₹4.50 Crores',
  deadline: '2026-10-15T18:00:00Z',
  created_at: '2026-08-20T10:00:00Z',
  requirements: MOCK_REQUIREMENTS,
};

export const MOCK_TENDERS: Tender[] = [
  MOCK_TENDER,
  {
    id: 'tender-gem-2026-surveillance',
    tender_number: 'GEM/2026/B/774012',
    title: 'Deployment of AI-Powered Integrated Surveillance and Perimeter Security System',
    department: 'Department of Physical Infrastructure & Surveillance',
    estimated_budget: 125000000,
    budget_formatted: '₹12.50 Crores',
    deadline: '2026-11-20T17:00:00Z',
    created_at: '2026-08-25T11:00:00Z',
    requirements: MOCK_REQUIREMENTS,
  },
  {
    id: 'tender-gem-2026-datacenter',
    tender_number: 'GEM/2026/B/651098',
    title: 'Procurement of High-Capacity Tier-IV Data Center SAN Storage and DR Replication Infrastructure',
    department: 'Department of Enterprise Systems & Data Infrastructure',
    estimated_budget: 85000000,
    budget_formatted: '₹8.50 Crores',
    deadline: '2026-10-30T15:00:00Z',
    created_at: '2026-09-01T09:30:00Z',
    requirements: MOCK_REQUIREMENTS,
  },
];

// Helper to construct standard documents
function makeDocs(bidderId: string, company: string, gstin: string, pan: string, turnoverCr: number, expYrs: number, oemStatus: 'MATCH' | 'MISMATCH' | 'MISSING', udyamNum: string, isDebarred = false, isGstCancelled = false) {
  const docs: any[] = [];

  // GST
  docs.push({
    id: `doc-${bidderId}-gst`,
    bidder_id: bidderId,
    file_name: `GST_Registration_Certificate_${company.replace(/\s+/g, '_')}.pdf`,
    doc_type: 'GST_CERT',
    file_url: `/docs/bidders/${bidderId}/gst_cert.pdf`,
    upload_date: '2026-09-02T14:15:00Z',
    page_count: 3,
    parsed_metadata: {
      extracted_entity_name: company,
      extracted_gstin: gstin,
      extracted_pan: pan,
      valid_from: '2017-08-14',
      valid_until: isGstCancelled ? '2023-01-01' : '2032-12-31',
      issuing_authority: 'Central GST Commissionerate',
      ocr_quality_score: 0.98,
    },
  });

  // Audit
  docs.push({
    id: `doc-${bidderId}-audit`,
    bidder_id: bidderId,
    file_name: `CA_Audited_Financial_Statement_FY23_FY25.pdf`,
    doc_type: 'FINANCIAL_AUDIT',
    file_url: `/docs/bidders/${bidderId}/financial_audit.pdf`,
    upload_date: '2026-09-02T14:20:00Z',
    page_count: 24,
    parsed_metadata: {
      extracted_entity_name: company,
      extracted_turnover: turnoverCr * 10000000,
      extracted_turnover_raw: `₹${turnoverCr.toFixed(2)} Crores (Average 3 FY)`,
      issuing_authority: 'Chartered Accountants Association (Valid UDIN)',
      ocr_quality_score: 0.97,
    },
  });

  // OEM MAF
  if (oemStatus !== 'MISSING') {
    docs.push({
      id: `doc-${bidderId}-oem`,
      bidder_id: bidderId,
      file_name: `OEM_Manufacturer_Authorization_Form.pdf`,
      doc_type: 'OEM_AUTH',
      file_url: `/docs/bidders/${bidderId}/oem_maf.pdf`,
      upload_date: '2026-09-02T14:22:00Z',
      page_count: 2,
      parsed_metadata: {
        extracted_entity_name: oemStatus === 'MISMATCH' ? `${company} Technologies Global` : company,
        oem_authorized_brands: ['Enterprise Server Series', 'Enterprise Switch N-Series'],
        issuing_authority: 'Tier-1 OEM Corporation (Enterprise Division)',
        ocr_quality_score: 0.96,
      },
    });
  }

  // Work Experience
  docs.push({
    id: `doc-${bidderId}-exp`,
    bidder_id: bidderId,
    file_name: `Past_Operational_Experience_Certificate.pdf`,
    doc_type: 'WORK_ORDER_EXPERIENCE',
    file_url: `/docs/bidders/${bidderId}/experience_cert.pdf`,
    upload_date: '2026-09-02T14:25:00Z',
    page_count: 8,
    parsed_metadata: {
      extracted_years_experience: expYrs,
      extracted_entity_name: company,
      ocr_quality_score: 0.95,
    },
  });

  // Affidavit
  docs.push({
    id: `doc-${bidderId}-affidavit`,
    bidder_id: bidderId,
    file_name: `Non_Debarment_Affidavit_Notarized.pdf`,
    doc_type: 'AFFIDAVIT_BLACKLIST',
    file_url: `/docs/bidders/${bidderId}/affidavit.pdf`,
    upload_date: '2026-09-02T14:28:00Z',
    page_count: 2,
    parsed_metadata: {
      extracted_entity_name: company,
      ocr_quality_score: 0.98,
    },
  });

  // Udyam
  docs.push({
    id: `doc-${bidderId}-udyam`,
    bidder_id: bidderId,
    file_name: `Udyam_Registration_Certificate_MSME.pdf`,
    doc_type: 'UDYAM',
    file_url: `/docs/bidders/${bidderId}/udyam.pdf`,
    upload_date: '2026-09-02T14:29:00Z',
    page_count: 2,
    parsed_metadata: {
      extracted_udyam_category: turnoverCr > 5 ? 'Medium' : 'Small',
      extracted_entity_name: company,
      ocr_quality_score: 0.99,
    },
  });

  return docs;
}

// Exactly 20 Fictional Bidders
export const MOCK_BIDDERS: Bidder[] = [
  {
    id: 'bidder-01',
    bidder_code: 'BIDDER-ABCD-001',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'ABCD Technologies',
    gst_number: '07AAAAA0000A1Z5',
    pan_number: 'AAAAA0000A',
    udyam_registration: 'UDYAM-AA-01-0000001',
    cin_number: 'U72200AA2017PTC000001',
    contact_person: 'Authorized Representative - ABCD',
    contact_email: 'contact@abcd.example',
    submission_date: '2026-09-02T14:30:00Z',
    overall_score: 100,
    compliance_score: 100,
    complianceScore: 100,
    risk_level: 'LOW',
    officer_decision: 'QUALIFIED',
    decision_notes: 'Automated verification completed: 100% clause compliance and green external registries.',
    documents: makeDocs('bidder-01', 'ABCD Technologies', '07AAAAA0000A1Z5', 'AAAAA0000A', 5.2, 7, 'MATCH', 'UDYAM-AA-01-0000001'),
  },
  {
    id: 'bidder-02',
    bidder_code: 'BIDDER-BCDE-002',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'BCDE Solutions',
    gst_number: '27BBBBB0000B1ZQ',
    pan_number: 'BBBBB0000B',
    udyam_registration: 'UDYAM-BB-02-0000002',
    cin_number: 'U72900BB2019PTC000002',
    contact_person: 'Authorized Representative - BCDE',
    contact_email: 'contact@bcde.example',
    submission_date: '2026-09-03T11:15:00Z',
    overall_score: 76,
    compliance_score: 76,
    complianceScore: 76,
    risk_level: 'MEDIUM',
    officer_decision: 'CLARIFICATION_REQUESTED',
    decision_notes: 'Entity name variation detected between GST and OEM authorization form. Officer clarification initiated.',
    documents: makeDocs('bidder-02', 'BCDE Solutions', '27BBBBB0000B1ZQ', 'BBBBB0000B', 3.15, 5, 'MISMATCH', 'UDYAM-BB-02-0000002'),
  },
  {
    id: 'bidder-03',
    bidder_code: 'BIDDER-CDEF-003',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'CDEF Industries',
    gst_number: '33CCCCC0000C1ZM',
    pan_number: 'CCCCC0000C',
    udyam_registration: 'UDYAM-CC-03-0000003',
    cin_number: 'U72200CC2015PLC000003',
    contact_person: 'Authorized Representative - CDEF',
    contact_email: 'contact@cdef.example',
    submission_date: '2026-09-04T09:40:00Z',
    overall_score: 28,
    compliance_score: 28,
    complianceScore: 28,
    risk_level: 'HIGH',
    officer_decision: 'DISQUALIFIED',
    decision_notes: 'Mandatory statutory rejection: Vendor is listed in CPPP Debarment registry. GST registration is cancelled.',
    documents: makeDocs('bidder-03', 'CDEF Industries', '33CCCCC0000C1ZM', 'CCCCC0000C', 1.8, 3, 'MISSING', 'UDYAM-CC-03-0000003', true, true),
  },
  {
    id: 'bidder-04',
    bidder_code: 'BIDDER-DEFG-004',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'DEFG Systems',
    gst_number: '06DDDDD0000D1Z8',
    pan_number: 'DDDDD0000D',
    udyam_registration: 'UDYAM-DD-04-0000004',
    cin_number: 'U72900DD2018PTC000004',
    contact_person: 'Authorized Representative - DEFG',
    contact_email: 'contact@defg.example',
    submission_date: '2026-09-04T12:20:00Z',
    overall_score: 94,
    compliance_score: 94,
    complianceScore: 94,
    risk_level: 'LOW',
    officer_decision: 'QUALIFIED',
    decision_notes: 'Full compliance on financial turnover (₹5.8 Cr), experience (7 yrs), and verified OEM authorization.',
    documents: makeDocs('bidder-04', 'DEFG Systems', '06DDDDD0000D1Z8', 'DDDDD0000D', 5.8, 7, 'MATCH', 'UDYAM-DD-04-0000004'),
  },
  {
    id: 'bidder-05',
    bidder_code: 'BIDDER-EFGH-005',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'EFGH Enterprises',
    gst_number: '29EEEEE0000E1Z2',
    pan_number: 'EEEEE0000E',
    udyam_registration: 'UDYAM-EE-05-0000005',
    cin_number: 'U72200EE2016PTC000005',
    contact_person: 'Authorized Representative - EFGH',
    contact_email: 'contact@efgh.example',
    submission_date: '2026-09-04T15:10:00Z',
    overall_score: 91,
    compliance_score: 91,
    complianceScore: 91,
    risk_level: 'LOW',
    officer_decision: 'QUALIFIED',
    decision_notes: 'Verified MSME enterprise with 6 years operational history and ₹4.2 Cr turnover.',
    documents: makeDocs('bidder-05', 'EFGH Enterprises', '29EEEEE0000E1Z2', 'EEEEE0000E', 4.2, 6, 'MATCH', 'UDYAM-EE-05-0000005'),
  },
  {
    id: 'bidder-06',
    bidder_code: 'BIDDER-FGHI-006',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'FGHI Digital',
    gst_number: '19FFFFF0000F1Z6',
    pan_number: 'FFFFF0000F',
    udyam_registration: 'UDYAM-FF-06-0000006',
    cin_number: 'U72400FF2017PTC000006',
    contact_person: 'Authorized Representative - FGHI',
    contact_email: 'contact@fghi.example',
    submission_date: '2026-09-05T09:00:00Z',
    overall_score: 88,
    compliance_score: 88,
    complianceScore: 88,
    risk_level: 'LOW',
    officer_decision: 'QUALIFIED',
    decision_notes: 'All mandatory RFP clauses verified. Tier-1 OEM MAF validated without deviations.',
    documents: makeDocs('bidder-06', 'FGHI Digital', '19FFFFF0000F1Z6', 'FFFFF0000F', 3.9, 6, 'MATCH', 'UDYAM-FF-06-0000006'),
  },
  {
    id: 'bidder-07',
    bidder_code: 'BIDDER-GHIJ-007',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'GHIJ Innovations',
    gst_number: '24GGGGG0000G1ZA',
    pan_number: 'GGGGG0000G',
    udyam_registration: 'UDYAM-GG-07-0000007',
    cin_number: 'U72200GG2019PTC000007',
    contact_person: 'Authorized Representative - GHIJ',
    contact_email: 'contact@ghij.example',
    submission_date: '2026-09-05T10:30:00Z',
    overall_score: 85,
    compliance_score: 85,
    complianceScore: 85,
    risk_level: 'LOW',
    officer_decision: 'QUALIFIED',
    decision_notes: 'Eligible technical bid with valid Udyam MSE preference applied.',
    documents: makeDocs('bidder-07', 'GHIJ Innovations', '24GGGGG0000G1ZA', 'GGGGG0000G', 3.6, 5, 'MATCH', 'UDYAM-GG-07-0000007'),
  },
  {
    id: 'bidder-08',
    bidder_code: 'BIDDER-HIJK-008',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'HIJK Solutions',
    gst_number: '09HHHHH0000H1ZE',
    pan_number: 'HHHHH0000H',
    udyam_registration: 'UDYAM-HH-08-0000008',
    cin_number: 'U72900HH2020PTC000008',
    contact_person: 'Authorized Representative - HIJK',
    contact_email: 'contact@hijk.example',
    submission_date: '2026-09-05T11:45:00Z',
    overall_score: 82,
    compliance_score: 82,
    complianceScore: 82,
    risk_level: 'MEDIUM',
    officer_decision: 'CLARIFICATION_REQUESTED',
    decision_notes: 'Borderline 3-year average turnover (₹2.95 Cr vs required ₹3.0 Cr). Financial re-verification requested.',
    documents: makeDocs('bidder-08', 'HIJK Solutions', '09HHHHH0000H1ZE', 'HHHHH0000H', 2.95, 5, 'MATCH', 'UDYAM-HH-08-0000008'),
  },
  {
    id: 'bidder-09',
    bidder_code: 'BIDDER-IJKL-009',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'IJKL Technologies',
    gst_number: '36IIIII0000I1Z4',
    pan_number: 'IIIII0000I',
    udyam_registration: 'UDYAM-II-09-0000009',
    cin_number: 'U72200II2018PTC000009',
    contact_person: 'Authorized Representative - IJKL',
    contact_email: 'contact@ijkl.example',
    submission_date: '2026-09-05T14:15:00Z',
    overall_score: 79,
    compliance_score: 79,
    complianceScore: 79,
    risk_level: 'MEDIUM',
    officer_decision: 'CLARIFICATION_REQUESTED',
    decision_notes: 'Past experience work completion certificate date ambiguity. Officer clarification notice issued.',
    documents: makeDocs('bidder-09', 'IJKL Technologies', '36IIIII0000I1Z4', 'IIIII0000I', 3.4, 4, 'MATCH', 'UDYAM-II-09-0000009'),
  },
  {
    id: 'bidder-10',
    bidder_code: 'BIDDER-JKLM-010',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'JKLM Systems',
    gst_number: '10JJJJJ0000J1Z9',
    pan_number: 'JJJJJ0000J',
    udyam_registration: 'UDYAM-JJ-10-0000010',
    cin_number: 'U72900JJ2019PTC000010',
    contact_person: 'Authorized Representative - JKLM',
    contact_email: 'contact@jklm.example',
    submission_date: '2026-09-05T16:00:00Z',
    overall_score: 72,
    compliance_score: 72,
    complianceScore: 72,
    risk_level: 'MEDIUM',
    officer_decision: 'CLARIFICATION_REQUESTED',
    decision_notes: 'Affidavit non-blacklisting notarization date precedes RFP notification. Formal response sought.',
    documents: makeDocs('bidder-10', 'JKLM Systems', '10JJJJJ0000J1Z9', 'JJJJJ0000J', 3.2, 5, 'MATCH', 'UDYAM-JJ-10-0000010'),
  },
  {
    id: 'bidder-11',
    bidder_code: 'BIDDER-KLMN-011',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'KLMN Enterprises',
    gst_number: '08KKKKK0000K1ZC',
    pan_number: 'KKKKK0000K',
    udyam_registration: 'UDYAM-KK-11-0000011',
    cin_number: 'U72200KK2015PTC000011',
    contact_person: 'Authorized Representative - KLMN',
    contact_email: 'contact@klmn.example',
    submission_date: '2026-09-06T09:30:00Z',
    overall_score: 92,
    compliance_score: 92,
    complianceScore: 92,
    risk_level: 'LOW',
    officer_decision: 'QUALIFIED',
    decision_notes: 'Turnover ₹7.1 Cr, active GSTIN, clear CPPP debarment status. Recommended for financial opening.',
    documents: makeDocs('bidder-11', 'KLMN Enterprises', '08KKKKK0000K1ZC', 'KKKKK0000K', 7.1, 8, 'MATCH', 'UDYAM-KK-11-0000011'),
  },
  {
    id: 'bidder-12',
    bidder_code: 'BIDDER-LMNO-012',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'LMNO Technologies',
    gst_number: '32LLLLL0000L1ZG',
    pan_number: 'LLLLL0000L',
    udyam_registration: 'UDYAM-LL-12-0000012',
    cin_number: 'U72400LL2017PTC000012',
    contact_person: 'Authorized Representative - LMNO',
    contact_email: 'contact@lmno.example',
    submission_date: '2026-09-06T11:00:00Z',
    overall_score: 89,
    compliance_score: 89,
    complianceScore: 89,
    risk_level: 'LOW',
    officer_decision: 'QUALIFIED',
    decision_notes: 'Statutory compliance confirmed with 99% GST return filing regularity score.',
    documents: makeDocs('bidder-12', 'LMNO Technologies', '32LLLLL0000L1ZG', 'LLLLL0000L', 4.5, 6, 'MATCH', 'UDYAM-LL-12-0000012'),
  },
  {
    id: 'bidder-13',
    bidder_code: 'BIDDER-MNOP-013',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'MNOP Solutions',
    gst_number: '21MMMMM0000M1ZK',
    pan_number: 'MMMMM0000M',
    udyam_registration: 'UDYAM-MM-13-0000013',
    cin_number: 'U72900MM2018PTC000013',
    contact_person: 'Authorized Representative - MNOP',
    contact_email: 'contact@mnop.example',
    submission_date: '2026-09-06T13:45:00Z',
    overall_score: 68,
    compliance_score: 68,
    complianceScore: 68,
    risk_level: 'MEDIUM',
    officer_decision: 'CLARIFICATION_REQUESTED',
    decision_notes: 'Quarterly GST filing frequency flagged for review. Tax clearance certificate requested.',
    documents: makeDocs('bidder-13', 'MNOP Solutions', '21MMMMM0000M1ZK', 'MMMMM0000M', 3.3, 5, 'MATCH', 'UDYAM-MM-13-0000013'),
  },
  {
    id: 'bidder-14',
    bidder_code: 'BIDDER-NOPQ-014',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'NOPQ Industries',
    gst_number: '23NNNNN0000N1ZO',
    pan_number: 'NNNNN0000N',
    udyam_registration: 'UDYAM-NN-14-0000014',
    cin_number: 'U72200NN2019PTC000014',
    contact_person: 'Authorized Representative - NOPQ',
    contact_email: 'contact@nopq.example',
    submission_date: '2026-09-06T15:20:00Z',
    overall_score: 65,
    compliance_score: 65,
    complianceScore: 65,
    risk_level: 'MEDIUM',
    officer_decision: 'CLARIFICATION_REQUESTED',
    decision_notes: 'OEM Authorization Form specifies non-exclusive distributorship. Clause R005 confirmation pending.',
    documents: makeDocs('bidder-14', 'NOPQ Industries', '23NNNNN0000N1ZO', 'NNNNN0000N', 3.1, 5, 'MISMATCH', 'UDYAM-NN-14-0000014'),
  },
  {
    id: 'bidder-15',
    bidder_code: 'BIDDER-OPQR-015',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'OPQR Systems',
    gst_number: '03OOOOO0000O1ZS',
    pan_number: 'OOOOO0000O',
    udyam_registration: 'UDYAM-OO-15-0000015',
    cin_number: 'U72900OO2016PTC000015',
    contact_person: 'Authorized Representative - OPQR',
    contact_email: 'contact@opqr.example',
    submission_date: '2026-09-07T10:00:00Z',
    overall_score: 96,
    compliance_score: 96,
    complianceScore: 96,
    risk_level: 'LOW',
    officer_decision: 'QUALIFIED',
    decision_notes: 'Substantial financial turnover (₹9.4 Cr) and 8 years public sector project experience.',
    documents: makeDocs('bidder-15', 'OPQR Systems', '03OOOOO0000O1ZS', 'OOOOO0000O', 9.4, 8, 'MATCH', 'UDYAM-OO-15-0000015'),
  },
  {
    id: 'bidder-16',
    bidder_code: 'BIDDER-PQRS-016',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'PQRS Innovations',
    gst_number: '01PPPPP0000P1ZW',
    pan_number: 'PPPPP0000P',
    udyam_registration: 'UDYAM-PP-16-0000016',
    cin_number: 'U72200PP2017PTC000016',
    contact_person: 'Authorized Representative - PQRS',
    contact_email: 'contact@pqrs.example',
    submission_date: '2026-09-07T12:30:00Z',
    overall_score: 86,
    compliance_score: 86,
    complianceScore: 86,
    risk_level: 'LOW',
    officer_decision: 'QUALIFIED',
    decision_notes: 'Udyam Small Enterprise status validated. Zero negative audit exceptions.',
    documents: makeDocs('bidder-16', 'PQRS Innovations', '01PPPPP0000P1ZW', 'PPPPP0000P', 3.8, 6, 'MATCH', 'UDYAM-PP-16-0000016'),
  },
  {
    id: 'bidder-17',
    bidder_code: 'BIDDER-QRST-017',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'QRST Enterprises',
    gst_number: '04QQQQQ0000Q1Z0',
    pan_number: 'QQQQQ0000Q',
    udyam_registration: 'UDYAM-QQ-17-0000017',
    cin_number: 'U72400QQ2020PTC000017',
    contact_person: 'Authorized Representative - QRST',
    contact_email: 'contact@qrst.example',
    submission_date: '2026-09-07T14:45:00Z',
    overall_score: 42,
    compliance_score: 42,
    complianceScore: 42,
    risk_level: 'HIGH',
    officer_decision: 'DISQUALIFIED',
    decision_notes: 'Disqualified: Missing OEM MAF certificate and average turnover below ₹1.5 Cr minimum threshold.',
    documents: makeDocs('bidder-17', 'QRST Enterprises', '04QQQQQ0000Q1Z0', 'QQQQQ0000Q', 1.4, 2, 'MISSING', 'UDYAM-QQ-17-0000017'),
  },
  {
    id: 'bidder-18',
    bidder_code: 'BIDDER-RSTU-018',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'RSTU Technologies',
    gst_number: '20RRRRR0000R1Z5',
    pan_number: 'RRRRR0000R',
    udyam_registration: 'UDYAM-RR-18-0000018',
    cin_number: 'U72200RR2015PLC000018',
    contact_person: 'Authorized Representative - RSTU',
    contact_email: 'contact@rstu.example',
    submission_date: '2026-09-07T16:15:00Z',
    overall_score: 35,
    compliance_score: 35,
    complianceScore: 35,
    risk_level: 'HIGH',
    officer_decision: 'DISQUALIFIED',
    decision_notes: 'Disqualified: GST Registration expired on 2023-12-31 and non-debarment affidavit absent.',
    documents: makeDocs('bidder-18', 'RSTU Technologies', '20RRRRR0000R1Z5', 'RRRRR0000R', 2.1, 4, 'MISSING', 'UDYAM-RR-18-0000018', false, true),
  },
  {
    id: 'bidder-19',
    bidder_code: 'BIDDER-STUV-019',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'STUV Solutions',
    gst_number: '22SSSSS0000S1Z9',
    pan_number: 'SSSSS0000S',
    udyam_registration: 'UDYAM-SS-19-0000019',
    cin_number: 'U72900SS2018PTC000019',
    contact_person: 'Authorized Representative - STUV',
    contact_email: 'contact@stuv.example',
    submission_date: '2026-09-08T09:15:00Z',
    overall_score: 22,
    compliance_score: 22,
    complianceScore: 22,
    risk_level: 'HIGH',
    officer_decision: 'DISQUALIFIED',
    decision_notes: 'CRITICAL REJECTION: Debarred vendor under CPPP Debarment Order CPA/PROC/DEBAR/2024/042.',
    documents: makeDocs('bidder-19', 'STUV Solutions', '22SSSSS0000S1Z9', 'SSSSS0000S', 2.5, 3, 'MATCH', 'UDYAM-SS-19-0000019', true),
  },
  {
    id: 'bidder-20',
    bidder_code: 'BIDDER-TUVW-020',
    tender_id: 'tender-gem-2026-cloud',
    company_name: 'TUVW Systems',
    gst_number: '18TTTTT0000T1ZD',
    pan_number: 'TTTTT0000T',
    udyam_registration: 'UDYAM-TT-20-0000020',
    cin_number: 'U72200TT2020PTC000020',
    contact_person: 'Authorized Representative - TUVW',
    contact_email: 'contact@tuvw.example',
    submission_date: '2026-09-08T11:30:00Z',
    overall_score: 18,
    compliance_score: 18,
    complianceScore: 18,
    risk_level: 'HIGH',
    officer_decision: 'DISQUALIFIED',
    decision_notes: 'Disqualified: Multiple mandatory document falsification flags and zero verifiable CA audit statements.',
    documents: makeDocs('bidder-20', 'TUVW Systems', '18TTTTT0000T1ZD', 'TTTTT0000T', 0.8, 1, 'MISSING', 'UDYAM-TT-20-0000020', true, true),
  },
];

// Helper to generate audit logs for each bidder
function generateMockAuditLogs(): Record<string, AuditLog[]> {
  const logsMap: Record<string, AuditLog[]> = {};

  for (const b of MOCK_BIDDERS) {
    logsMap[b.id] = [
      {
        id: `log-${b.id}-1`,
        tender_id: b.tender_id,
        bidder_id: b.id,
        actor: 'SYSTEM',
        action: 'DOCUMENT_PACKET_INGESTION_COMPLETED',
        timestamp: '2026-09-08T12:00:00Z',
        metadata: {
          documents_processed: b.documents?.length || 5,
          ocr_engine: 'Hybrid LayoutLMv3 + PyMuPDF FastExtractor',
          avg_confidence: 0.97,
        },
      },
      {
        id: `log-${b.id}-2`,
        tender_id: b.tender_id,
        bidder_id: b.id,
        actor: 'SYSTEM',
        action: 'EXTERNAL_REGISTRY_ADAPTERS_EVALUATED',
        timestamp: '2026-09-08T12:00:02Z',
        metadata: {
          gstn_status: b.risk_level === 'HIGH' && b.overall_score < 30 ? 'CANCELLED' : 'ACTIVE',
          gstn_compliance_score: b.overall_score,
          udyam_category: b.overall_score > 80 ? 'Medium' : 'Small',
          debarment_status: b.overall_score < 30 ? 'DEBARRED' : 'CLEAR',
          execution_latency_ms: 295,
        },
      },
      {
        id: `log-${b.id}-3`,
        tender_id: b.tender_id,
        bidder_id: b.id,
        actor: 'SYSTEM',
        action: 'DETERMINISTIC_COMPLIANCE_RUN_COMPLETED',
        timestamp: '2026-09-08T12:00:04Z',
        metadata: {
          score: b.overall_score,
          risk_level: b.risk_level,
          mandatory_failures_count: b.risk_level === 'HIGH' ? 2 : 0,
          recommendation: b.officer_decision,
        },
      },
    ];

    if (b.officer_decision === 'CLARIFICATION_REQUESTED') {
      logsMap[b.id].push({
        id: `log-${b.id}-4`,
        tender_id: b.tender_id,
        bidder_id: b.id,
        actor: 'OFFICER',
        action: 'OFFICER_REQUESTED_CLARIFICATION',
        timestamp: '2026-09-08T14:30:00Z',
        metadata: {
          officer_name: 'ABCD',
          remarks: b.decision_notes,
        },
      });
    } else if (b.officer_decision === 'DISQUALIFIED') {
      logsMap[b.id].push({
        id: `log-${b.id}-4`,
        tender_id: b.tender_id,
        bidder_id: b.id,
        actor: 'OFFICER',
        action: 'OFFICER_DISQUALIFICATION_CONFIRMED',
        timestamp: '2026-09-08T16:00:00Z',
        metadata: {
          officer_name: 'ABCD',
          remarks: b.decision_notes,
        },
      });
    }
  }

  return logsMap;
}

export const MOCK_AUDIT_LOGS: Record<string, AuditLog[]> = generateMockAuditLogs();
